### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabriel-maxx** [Flerov/HideProcessDriver#1]
Hello, I would like to know how do I get "The Unique Process Id" of my machine? I'm using windows 11 x64 10.0.22621.1344

**Comment by vitri0l** [comment]
Attach WinDbg - Kernel Debugger to your machine and issue the command:
dt nt!_EPROCESS
This will generate a response. There you can search for UniqueProcessId - Field and get the corresponding offset for your version

**Comment by gabriel-maxx** [comment]
> Attach WinDbg - Kernel Debugger to your machine and issue the command: dt nt!_EPROCESS This will generate a response. There you can search for UniqueProcessId - Field and get the corresponding offset for your version

thanks for answering but i have one more question,if i add the OFFSET from the latest version of windows will the driver work on all previous versions?

**Comment by vitri0l** [comment]
> > Attach WinDbg - Kernel Debugger to your machine and issue the command: dt nt!_EPROCESS This will generate a response. There you can search for UniqueProcessId - Field and get the corresponding offset for your version
> 
> thanks for answering but i have one more question,if i add the OFFSET from the latest version of windows will the driver work on all previous versions?

It may hold on different Minor Versions. But mostly they change on the Major Versions. Ie if you want to make it work in Win10 you'll need to update the offsets. It wont work on all previous versions

**Comment by gabriel-maxx** [comment]
> > > Attach WinDbg - Kernel Debugger to your machine and issue the command: dt nt!_EPROCESS This will generate a response. There you can search for UniqueProcessId - Field and get the corresponding offset for your version
> > 
> > 
> > thanks for answering but i have one more question,if i add the OFFSET from the latest version of windows will the driver work on all previous versions?
> 
> It may hold on different Minor Versions. But mostly they change on the Major Versions. Ie if you want to make it work in Win10 you'll need to update the offsets. It wont work on all previous versions

so if i want it to be compatible with all windows versions for example from 7 to 11 i have to keep looking for the offset using windbg one by one, i mean isn't there a faster way to do that? and also how would the code look for example to specify the offset of several versions? because in the code only one offset version is defined...

**Comment by vitri0l** [comment]
Hm aint easy. You can scan through memory and look for what u need. Or you parse symbols. Its a pretty difficult challenge especially the later... Otherwise what is - I guess for you - more doable is to check the version and then use conditions to determine what offset to use. You can also find your own creative way, just keept trying.
But for what this can be used for.... Thats as far as I wanna help you without knowing who you are or what you want to achieve with this ;)

**Comment by gabriel-maxx** [comment]
@Flerov I have one last question, what do I have to edit in the driver code to hide a process by name instead of PID for example: find the process called test.exe and hide it.

**Comment by vitri0l** [comment]
Invest some time with the structure _EPROCESS I already told you about. It contains many fields one of them holds the files name. From that field you can just compare it to your targets name. But you'll need to change the communication part, from sending the PIDs number to a string. Otherwise do it from the user-mode part. It will not be difficult to find examples of getting the PID from a process' name then you dont need to change as much of the code...
Experiment around. I recommend you to first try the second approach and then when you have it working and understand it, try to achieve the same from kernel, its a neat challenge for your level and definitly doable

**Comment by gabriel-maxx** [comment]
@Flerov thanks for your knowledge
